name: Build

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            .next
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: install
        run: yarn install

      - name: build
        run: yarn build

      - name: lint
        run: yarn lint

      - name: export
        run: yarn export
